version: "3.7"

services:

  db:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: Admin123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.data:/var/lib/mysql
    networks:
      - default-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Admin123
    networks:
      - default-network

  node:
    image: node:18
    working_dir: /var/www/html
    tty: true
    environment:
      - YBUILD=yarn start:dev
    user: ${DOCKER_USER:-1000}:${DOCKER_USER:-1000}
    ports:
      - ${PORT}:3000
      - '5555:5555'
    volumes:
      - .:/var/www/html
    command: [ "bash", ".bin/build.sh" ]
    networks:
      - default-network

  redis:
    image: redis:7.0.5
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}
    networks:
      - default-network
    volumes:
      - ./cache:/data/cache
    # command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    
networks:
  default-network:
    driver: bridge
